name: mlenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
# Mostly used Python libs
  - python
  - autopep8
  - black
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  # - pip:
    # - tensorflow==2.0
# IPython modules
  - ipywidgets
  - jupyterlab
  # - jupyterlab-git
  # - jupyterlab-nvdashboard
  # - jupyterlab-lsp
  # - python-language-server
# Machine learning modules
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - torchmetrics
  # - pytorch-lightning
  # - torchvision
# GPU 
  # - cudatoolkit